import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml.toml"
]

[font]
normal = { family = "MesloLGS Nerd Font", style = "Normal" }
bold = { family = "MesloLGS Nerd Font", style="Bold"}
italic = { family = "MesloLGS Nerd Font", style="italic"}
size=11

[window]
padding = { x = 15, y = 15 }
